/*
 * Class name:
 * Date:
 * Programmer: Lara Aras
 * Description: 
 */
package animalsearchengine;

import javax.swing.*;
import java.util.*;

/**
 * Panel containing form for admin login.
 *
 * @author laraa
 */
public class Login extends javax.swing.JPanel {

    private JFrame mainFrame;
    private JPanel mainPanel;

    /**
     * Version: Project 1
     * <p>
     * Date: 04/10/2021
     * <p>
     * Creates new form Login
     *
     * @author Lara Aras
     * @param mainFrame
     * @param mainPanel
     */
    public Login(JFrame mainFrame, JPanel mainPanel) {
        this.mainFrame = mainFrame;
        this.mainPanel = mainPanel;

        initComponents();
    }

    /**
     * Version: Project 1
     * <p>
     * Date: 04/10/2021
     * <p>
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchHeadingLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        submitLoginButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 400));

        searchHeadingLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        searchHeadingLabel.setText("Admin Login");

        usernameLabel.setText("Username:");

        passwordLabel.setText("Password:");

        submitLoginButton.setText("Submit");
        submitLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(passwordLabel)
                        .addComponent(usernameLabel)
                        .addComponent(usernameField)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(submitLoginButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(searchHeadingLabel)
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(searchHeadingLabel)
                .addGap(76, 76, 76)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitLoginButton)
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitLoginButtonActionPerformed
        String username = usernameField.getText();
        String password = String.valueOf(passwordField.getPassword());

        HashMap request = new HashMap();
        request.put("action", "login");
        request.put("username", username);
        request.put("password", password);

        /* Send request to server */
        Client client = new Client();
        String response = client.sendRequest(request);
        if (response.equals("success")) {
            mainPanel.removeAll();
            mainPanel.add(new DatabaseAdmin());
            mainFrame.pack();
            mainFrame.repaint();
        } else if (!response.equals("server off")) {
            /* If the error was not caused by the server being off */
            JOptionPane.showMessageDialog(this, "You have entered invalid login "
                    + "credentials. Please try again.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

        /* Set static variable loggedIn to true after first login so that 
           user only has to log in once */
        AnimalSearchEngine.loggedIn = true;
    }//GEN-LAST:event_submitLoginButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel searchHeadingLabel;
    private javax.swing.JButton submitLoginButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
